version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: sisand_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sisand_airlines
    ports:
      - "5433:5432"   # usa 5433 no host pra evitar conflito
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
