<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SisandAirlines.Domain\SisandAirlines.Domain.csproj" />
    <ProjectReference Include="..\SisandAirlines.Infrastructure\SisandAirlines.Infrastructure.csproj" />
  </ItemGroup>

</Project>
